server:
  port: 8090

spring:
  application:
    name: commandes-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/restaurantDB

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: commande-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

