version: '3.8'
services:
  eureka:
    build:
      context: ./Eureka-Server
    image: eureka-server
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - mynetwork

  api-gateway:
    build:
      context: ./API_Gateway
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
    networks:
      - mynetwork


  angular-frontend:
    image: angular-frontend
    container_name: angular-frontend
    build: ./Front-End
    ports:
      - "4200:4200"
    depends_on:
      - api-gateway
    networks:
      - mynetwork
    environment:
      - API_BASE_URL=http://api-gateway:8081
      - CHOKIDAR_USEPOLLING=true # Pour surveiller les fichiers sous Docker




  db:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reclamation_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  reclamation-service:
    build:
      context: ./Reclamation_Service
    image: reclamation-service
    container_name: reclamation-service
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/reclamation_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge