server:
  port: 8081  

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:8081"
              - "http://angular-frontend:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: reclamations-service
          uri: lb://reclamations-service
          predicates:
            - Path=/reclamations/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - RequestSize=10MB
            - name: CircuitBreaker
              args:
                name: reclamationsCB
                fallbackUri: forward:/fallback/reclamations

        - id: commandes-service
          uri: lb://commandes-service
          predicates:
            - Path=/commandes/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - RequestSize=10MB
            - name: CircuitBreaker
              args:
                name: commandesCB
                fallbackUri: forward:/fallback/commandes

  # Timeouts pour éviter que les requêtes bloquent
  httpclient:
    connect-timeout: 5000
    response-timeout: 10s

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    hostname: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      reclamationsCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
      commandesCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s