server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native  # Utiliser le profil native au lieu de Git
  cloud:
    config:
      server:
        native:
          search-locations: file:///config-repo/{application}

# Désactivation de l'enregistrement initial avec Eureka pour éviter les erreurs au démarrage
eureka:
  client:
    enabled: false  # Désactivation de l'enregistrement initial
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka:8761/eureka/}

# Configuration pour exposer les endpoints Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always